global:
  scrape_interval: 15s
  scrape_timeout: 15s
scrape_configs:
- job_name: node
  static_configs:
  - labels:
      instance: nixos-desktop
    targets:
    - 192.168.1.12:9100
  - labels:
      instance: nixos-build01
    targets:
    - 192.168.1.14:9100
  - labels:
      instance: nixos-ext
    targets:
    - 192.168.1.13:9100
  - labels:
      instance: nixos-cantcache-me
    targets:
    - 65.109.152.76:9100
- job_name: zfs
  static_configs:
  - labels:
      instance: nixos-desktop
    targets:
    - 192.168.1.12:9134
  - labels:
      instance: nixos-build01
    targets:
    - 192.168.1.14:9134
  - labels:
      instance: nixos-ext
    targets:
    - 192.168.1.13:9134
  - labels:
      instance: nixos-cantcache-me
    targets:
    - 65.109.152.76:9134