keys:
  machines:
    - &nixos-build01 age1lmcvfc07ggerxgsrzq2nvc8t6hm44n68ajsh0qr7rs32r6pez5asshkyvf
    - &nixos-desktop age1azuwgsgd2vhgkcuqagxefjt4peh9hz9ddmpcxd8p763qrefd8ddqas32ef
    - &nixos-ext age12z4wlayqratlswq0gq43ps6sp084r7mxh9ukjcczv09cry4skemqr9ekdr
creation_rules:
  - path_regex: modules/nix/cantcacheme/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *nixos-desktop
  - path_regex: modules/nix/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-build01
          - *nixos-desktop
          - *nixos-ext
  - path_regex: devices/nixos-build01/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-build01
  - path_regex: devices/nixos-desktop/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-desktop
  - path_regex: devices/nixos-ext/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-ext
