keys:
  machines:
    - &nixos-build01 age1lmcvfc07ggerxgsrzq2nvc8t6hm44n68ajsh0qr7rs32r6pez5asshkyvf
    - &nixos-cantcache-me age1cn4t725k7hpy87hf5ea40z7mdydtkaq3k28gxd08mjd6u3utc9nqnk5pnr
    - &nixos-desktop age1azuwgsgd2vhgkcuqagxefjt4peh9hz9ddmpcxd8p763qrefd8ddqas32ef
    - &nixos-ext age12z4wlayqratlswq0gq43ps6sp084r7mxh9ukjcczv09cry4skemqr9ekdr
    - &nixos-orin age1leyyqreersrk2k6xffmfp2lqflxe6ss8lftwy3lfejklg84zuc7qdzk990
creation_rules:
  - path_regex: modules/nix/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-build01
          - *nixos-cantcache-me
          - *nixos-desktop
          - *nixos-ext
  - path_regex: modules/services/binary-cache/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-cantcache-me
  - path_regex: modules/services/binary-cache/attic-watch-store/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-build01
          - *nixos-desktop
          - *nixos-ext
  - path_regex: modules/services/monitoring/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-build01
          - *nixos-cantcache-me
          - *nixos-desktop
          - *nixos-ext
  - path_regex: devices/nixos-build01/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-build01
  - path_regex: devices/nixos-cantcache-me/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-cantcache-me
  - path_regex: devices/nixos-desktop/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-desktop
  - path_regex: devices/nixos-ext/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-ext
  - path_regex: devices/nixos-orin/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-orin
